---
- name: set ipfowarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    create: true
    state: present
    line: net.ipv4.ip_forward=1
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl
