---
- hosts: client
  become: true
  tasks:
  - name: Copy client network config
    ansible.builtin.copy:
      src: "eth2_client"
      dest: "/etc/network/interfaces.d/eth2"
      mode: '0644'
      validate: /usr/sbin/ifup --no-act -i %s eth2
    notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.service:
        name: networking
        state: restarted

- hosts: router
  become: true
  tasks:
  - name: Copy router network config
    ansible.builtin.copy:
      src: "eth3_router" 
      dest: "/etc/network/interfaces.d/eth3"
      mode: '0644'
      validate: /usr/sbin/ifup --no-act -i %s eth3
    notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.service:
        name: networking
        state: restarted

- hosts: server
  become: true
  tasks:
  - name: Copy server network config
    ansible.builtin.copy:
      src: "eth2_server"
      dest: "/etc/network/interfaces.d/eth2"
      mode: '0644'
      validate: /usr/sbin/ifup --no-act -i %s eth2
    notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.service:
        name: networking
        state: restarted
