---
- name: Configure eth1
  ansible.builtin.copy:
    src: eth1
    dest: /etc/network/interfaces.d/eth1
    mode: '0644'
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Configure eth2
  ansible.builtin.copy:
    src: eth2
    dest: /etc/network/interfaces.d/eth2
    mode: '0644'
    validate: /usr/sbin/ifup --no-act -i %s eth2
  notify: Restart Networking

- name: Configure eth3
  ansible.builtin.copy:
    src: eth3
    dest: /etc/network/interfaces.d/eth3
    mode: '0644'
    validate: /usr/sbin/ifup --no-act -i %s eth3
  notify: Restart Networking
