---
- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: eth1dhcp
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Installa get-users.sh
  copy:
    src: get-users.sh
    dest: /usr/bin/get-users.sh
    owner: root
    group: root
    mode: 0744

- name: Installa Systemd Unit per get-users
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    src: 'get-users.service'
    dest: '/etc/systemd/system/get-users.service'
  notify: Start get-users
