Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "router" do |machine|
    machine.vm.hostname = "router"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "server" do |machine|
    machine.vm.hostname = "server"
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
    machine.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress2", "0800278aea03"]
    end
  end

  (1..2).each do |i|
    config.vm.define "client#{i}" do |machine|
      machine.vm.hostname = "client#{i}"
	machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end
end
