---
- name: Copy 50-default.conf
  ansible.builtin.copy:
    src: 50-default.conf
    dest: /etc/rsyslog.d/50-default.conf
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

