---
- name: Install dnsmasq service
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Configure dnsmasq for eth1
  ansible.builtin.copy:
    src: lan1
    dest: /etc/dnsmasq.d/lan1.conf
    mode: '0644'
  notify: Restart dnsmasq

- name: Configure dnsmasq for eth2
  ansible.builtin.copy:
    src: lan2
    dest: /etc/dnsmasq.d/lan2.conf
    mode: '0644'
  notify: Restart dnsmasq
