# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
     vb.linked_clone = true
  end

  config.vm.define "router" do |machine|
    machine.vm.hostname = "router"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
    machine.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "Client1" do |machine|
    machine.vm.hostname = "Client1"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "Client2" do |machine|
    machine.vm.hostname = "Client2"
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "server" do |machine|
    machine.vm.hostname = "server"
    machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
    machine.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
    end
  end

end
