---
- name: Copy a new eth1 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r2eth1
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Copy a new eth2 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r2eth2
    dest: /etc/network/interfaces.d/eth2
    validate: /usr/sbin/ifup --no-act -i %s eth2
  notify: Restart Networking

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Configure dnsmasq
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq
