---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Ensure group dnsmasq exists
  ansible.builtin.group:
    name: dnsmasq
    state: present

- name: Create log file
  ansible.builtin.file:
    path: /var/log/dnsmasq.log
    state: touch
    owner: dnsmasq
    group: dnsmasq
    mode: '0644'

- name: Configure dnsmasq for LAN1 and LAN2
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: '0644'
  notify: Restart dnsmasq
