---
- name: Copy 50-default.conf
  become: true
  ansible.builtin.copy:
    src: 50-default.conf
    dest: /etc/rsyslog.d/50-default.conf

- name: Stop rsyslog
  ansible.builtin.command:
    cmd: systemctl stop rsyslog.service

- name: Stop syslog.socket
  ansible.builtin.command:
    cmd: systemctl stop syslog.socket

- name: Start rsyslog
  ansible.builtin.command:
    cmd: systemctl start rsyslog.service
