---
- name: Copy a new eth1 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r1eth1
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Copy a new eth2 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r1eth2
    dest: /etc/network/interfaces.d/eth2
    validate: /usr/sbin/ifup --no-act -i %s eth2
  notify: Restart Networking

- name: Copy sources.list
  become: true
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
  notify: Restart Networking

- name: "Update all packages"
  ansible.builtin.apt:
    update_cache: true

- name: Install snmp
  ansible.builtin.apt:
    name: snmp
    state: present

- name: Install snmp-mibs-downloader
  ansible.builtin.apt:
    name: snmp-mibs-downloader
    state: present

- name: Activate mibs
  ansible.builtin.command:
    cmd: sudo sed -i 's/mibs :/# mibs :/g' /etc/snmp/snmp.conf

- name: Copy rsyslog.conf
  become: true
  ansible.builtin.copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    
- name: Append public key
  ansible.builtin.lineinfile:
    line: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSQIG8eCX1xY2p4OAIjRthqivCyd+KZTpkkUhdND6L83DhHjumyzzzHw7mrhgUtks9wk91nAa2hnRvdWix4yjLQL9YP+icrIhqpBbAw4nsYn/8PwA7GXTiZ4iWggBD91XmSR+aAcTpOMmch13Dsi/Df8YZTy9y8DwYD0efHoFEpTzSg3g07TsJAtBheud0miAh2ky1q47eR8sRZ25FXH2S6VLquOLJ6TvZgmJhPOZf9sJRBlqjMqY8U2N58Z4sSYY191eqg8qJRWdAIf5kqTNLPnmGkecoHS5KzEF49mDywCBbbqFpIqz5vk7Y/3yLw6R6WGCLz7t8b4Fjj+BK82o8d3L0HeeD3yt1/liWfjP5c+dELpA9Ae60xawgQR6wWJsd2pglw7hGDhmPb+er5+XA3loPE/rjeSNgEpxSYuez2nQ13jdL3+Lz3FNNpeqIuqWhI38xCDj7AhtHWHHlhXvWTkrn6UEHa82jBbFxxj6QMZGONxXVdLX7wf7xRxQ4wExwr5Dulkxx2yfZyXma45FIegD7fBtMCymiMkXtvrgpX1oxhxHc0tE8V1mieb1FPsXICRFPY/JK/EB/OlmszQK+udxbzMC2elhOl2Zjl6KmO9G5yXTeFwmCTT4ooW0vRCFnR1l1oiDiCefOVCJt+lg1Qg0nkG9aCUyzG3NMRlq3oQ== My personal SSH key
    path: /home/vagrant/.ssh/authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys