# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "R" do |machine|
    machine.vm.hostname = "R"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
  end

  config.vm.define "S" do |machine|
    machine.vm.hostname = "R"
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
  end

  config.vm.define "C1" do |machine|
    machine.vm.hostname = "C1"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

end
