---
- hosts: router
  become: true
  roles:
   - common
   - netr1
   - ipforward
   - dnsmasqr1
   - ldap_server
   - agent

- hosts: client1
  become: true
  roles:
   - common
   - eth1dhcp
   - ldap_login
   - rsyslog_scrittura
   - controller

- hosts: server1
  become: true
  roles:
   - common
   - eth1dhcp
   - ldap_login
   - rsyslog_scrittura
   - controller

- hosts: server2
  become: true
  roles:
   - common
   - eth1dhcp
   - ldap_login
   - rsyslog_scrittura
   - controller

