---
- name: Installa rsyslog
  apt:
    update_cache: yes
    name: rsyslog
    state: latest

- name: Configura rsyslog
  copy:
    src: rsyslog.local.conf
    dest: /etc/rsyslog.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog
