---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Copy dnsmasq.conf
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: '0644'
  notify: Restart dnsmasq
