# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "router" do |machine|
    machine.vm.hostname = "router"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
  end

  (1..2).each do |i|
    config.vm.define "server#{i}" do |machine|
      machine.vm.hostname = "server#{i}"
	machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

  config.vm.define "client1" do |machine|
    machine.vm.hostname = "client1"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

end
