# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "debian/bookworm64"
   config.vm.provider "virtualbox" do |vb|
     vb.linked_clone = true
   end
 
   config.vm.define "router" do |router|
     router.vm.hostname = "router"
     router.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
     router.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
     router.vm.synced_folder ".", "/vagrant", disabled: true
     router.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
     end
   end
 
   config.vm.define "client" do |client|
     client.vm.hostname = "client"
     client.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
     client.vm.synced_folder ".", "/vagrant", disabled: true
     client.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
     end
     client.vm.provider "virtualbox" do |v|
       v.customize ["modifyvm", :id, "--macaddress2", "0800278aea03"]
     end
   end
 
   config.vm.define "server" do |server|
     server.vm.hostname = "server"
     server.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
     server.vm.synced_folder ".", "/vagrant", disabled: true
     server.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
     end
     server.vm.provider "virtualbox" do |v|
       v.customize ["modifyvm", :id, "--macaddress2", "080027ebcf52"]
     end
   end
 end