
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
   config.vm.provider "virtualbox" do |vb|
     vb.linked_clone = true
   end   

   config.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false

   config.vm.define "server" do |machine|
      machine.vm.hostname = "server"
      machine.vm.provision "ansible" do |ansible|
         ansible.playbook = "playbook.yml"
         config.vm.network "private_network", virtualbox__intnet: "LAN1"
      end
   end

   config.vm.define "client" do |machine|
      machine.vm.hostname = "client"
      machine.vm.provision "ansible" do |ansible|
         ansible.playbook = "playbook.yml"
         config.vm.network "private_network", virtualbox__intnet: "LAN1"
      end
   end
end
